name: Assemble Case Report
description: "Assemble les rapports par type en un CaseReport.md (résumé exécutif, IoC, score global, reco, gaps)"
inputs:
  case_path:
    description: "Chemin du case"
    required: true
runs:
  using: composite
  steps:
    - name: Assemble enriched CaseReport (no arrays, no awk)
      shell: bash
      run: |
        set -euo pipefail
        CASE="${{ inputs.case_path }}"
        OUT="$CASE/reports"
        mkdir -p "$OUT"
        NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

        get_score() {
          # retourne 0 si absent
          local f="$1"
          if [ -f "$f" ]; then
            grep -Eo '"risk_score"[[:space:]]*:[[:space:]]*[0-9]+' "$f" | head -n1 | grep -Eo '[0-9]+' || echo 0
          else
            echo 0
          fi
        }

        # chemins rapports unitaires
        RN="$CASE/outputs/per_type/network/report.json"
        RE="$CASE/outputs/per_type/endpoint/report.json"
        RS="$CASE/outputs/per_type/siem/report.json"
        RM="$CASE/outputs/per_type/mobile/report.json"

        # scores (0..100)
        SC_N="$(get_score "$RN")"
        SC_E="$(get_score "$RE")"
        SC_S="$(get_score "$RS")"
        SC_M="$(get_score "$RM")"

        # poids de base
        W_E=40; W_N=25; W_S=25; W_M=10

        # poids effectifs (0 si type absent)
        PE=0; PN=0; PS=0; PM=0
        [ -f "$RE" ] && PE=$W_E
        [ -f "$RN" ] && PN=$W_N
        [ -f "$RS" ] && PS=$W_S
        [ -f "$RM" ] && PM=$W_M

        # somme des poids
        SUMW=$((PE + PN + PS + PM))
        [ "$SUMW" -gt 0 ] || SUMW=1  # éviter /0

        # moyenne pondérée entière
        NUM=$(( SC_E*PE + SC_N*PN + SC_S*PS + SC_M*PM ))
        GLOBAL=$(( NUM / SUMW ))

        risk_level() {
          local x="$1"
          if   [ "$x" -ge 70 ]; then echo "HAUT"
          elif [ "$x" -ge 40 ]; then echo "MOYEN"
          elif [ "$x" -ge 15 ]; then echo "FAIBLE"
          else echo "NÉGLIGEABLE"; fi
        }
        GLOBAL_LVL="$(risk_level "$GLOBAL")"

        # Types analysés (jolie chaîne)
        TYPES_LIST=""
        [ -f "$RE" ] && TYPES_LIST="${TYPES_LIST}, endpoint"
        [ -f "$RN" ] && TYPES_LIST="${TYPES_LIST}, network"
        [ -f "$RS" ] && TYPES_LIST="${TYPES_LIST}, siem"
        [ -f "$RM" ] && TYPES_LIST="${TYPES_LIST}, mobile"
        TYPES_LIST="${TYPES_LIST#, }"
        [ -n "$TYPES_LIST" ] || TYPES_LIST="none"

        # IoC extraction simple
        IN="$CASE/inputs"
        IOC_FILE="$OUT/ioc_table.md"
        {
          echo "| Type | Valeur | Source | Timestamp indicatif |"
          echo "|------|--------|--------|----------------------|"
          if [ -d "$IN/network" ]; then
            grep -Eoh '[A-Za-z0-9.-]+\.(top|xyz|ru|cn|click|zip|mov|com|net|io)' "$IN/network"/* 2>/dev/null \
              | sort -u | head -n 50 | sed 's/.*/| Domaine | & | network | (voir fichier) |/'
            grep -Eoh '([0-9]{1,3}\.){3}[0-9]{1,3}' "$IN/network"/* 2>/dev/null \
              | sort -u | head -n 50 | sed 's/.*/| IP | & | network | (voir fichier) |/'
          fi
          grep -Eoh 'svc-[a-z0-9_-]+' "$IN"/endpoint/* "$IN"/siem/* 2>/dev/null \
            | sort -u | head -n 50 | sed 's/.*/| Compte | & | endpoint\/siem | (voir fichier) |/'
          grep -Eoh '\b(3389|445)\b' "$IN"/siem/* "$IN"/network/* 2>/dev/null \
            | sort -u | sed 's/.*/| Port | & | siem\/network | (voir fichier) |/'
          grep -Eoh 'powershell[[:space:]]*-enc|certutil[[:space:]]*-urlcache|bitsadmin|rundll32|rclone|vssadmin|bcdedit|ssh' "$IN"/endpoint/* 2>/dev/null \
            | sort -u | sed 's/.*/| Commande | & | endpoint | (timeline) |/'
        } > "$IOC_FILE" || true

        # Intégrité & gaps
        HASH_NOTE="Hash non fourni (à générer sur archives d'inputs)"
        [ -d "$CASE/10_Acquisition/Hashes" ] && HASH_NOTE="Hashes présents (vérifier SHA256 des archives)"
        GAP_LIST=""
        [ -f "$CASE/inputs/endpoint/timeline.csv" ] || GAP_LIST="${GAP_LIST}\n- Timeline endpoint manquante"
        [ -d "$CASE/inputs/network" ] || GAP_LIST="${GAP_LIST}\n- Artefacts réseau absents"
        [ -d "$CASE/inputs/siem" ] || GAP_LIST="${GAP_LIST}\n- Exports SIEM absents"
        [ -d "$CASE/inputs/mobile" ] || GAP_LIST="${GAP_LIST}\n- Exports mobile absents"
        [ -n "$GAP_LIST" ] || GAP_LIST="(Rien de bloquant détecté)"

        META_TZ="$(grep -E '^timezone:' -h "$CASE/metadata/case.yml" 2>/dev/null | awk '{print $2}' || true)"
        META_PER="$(grep -E '^period:'   -h "$CASE/metadata/case.yml" 2>/dev/null | awk '{print $2}' || true)"
        [ -n "${META_TZ:-}" ] || META_TZ="UTC"
        [ -n "${META_PER:-}" ] || META_PER="(période non précisée)"
        VERDICT="Probable activité malveillante — à confirmer"
        [ "$GLOBAL" -ge 70 ] && VERDICT="Activité malveillante probable (HAUT) — containment conseillé"

        CR="$OUT/CaseReport.md"
        {
          echo "# Case Report"
          echo "_Généré le: $NOW (UTC)_"
          echo
          echo "## Résumé exécutif"
          echo "- **Période** : $META_PER ($META_TZ)"
          echo "- **Verdict** : $VERDICT"
          echo "- **Risque global** : $GLOBAL ($GLOBAL_LVL)"
          echo "- **Types analysés** : $TYPES_LIST"
          echo "- **Prochaines actions (flash)** : voir Recommandations ci-dessous"
          echo
          echo "## Table d'IoC (extrait)"
          if [ -s "$IOC_FILE" ]; then
            cat "$IOC_FILE"
          else
            echo "_Aucun IoC extrait automatiquement._"
          fi
          echo
          echo "## Cohérence temporelle"
          echo "- Horodatages **$META_TZ** ; aligner SIEM / endpoint / réseau. Attention aux décalages locaux."
          echo
          echo "## Intégrité & traçabilité"
          echo "- $HASH_NOTE"
          echo
          echo "## Recommandations priorisées"
          echo "### Immédiat (0–24h)"
          echo "- Isoler l'hôte, geler preuves, réinit secrets"
          echo "- Bloquer domaines/IP observés (proxy/DNS/EDR)"
          echo "- Vérifier persistance (services, tâches planifiées)"
          echo
          echo "### Sous 7 jours"
          echo "- Durcir journaux (Sécurité/PowerShell), GPO"
          echo "- Revue comptes/groupes, renforcer MFA"
          echo
          echo "### Sous 30 jours"
          echo "- Surveiller IoC 30j (SIEM)"
          echo "- Playbooks & leçons apprises"
          echo
          echo "## Gaps / Manques"
          printf "%b\n" "$GAP_LIST"
          echo
          for TYPE in network endpoint siem mobile; do
            MD="$CASE/outputs/per_type/$TYPE/report.md"
            if [ -f "$MD" ]; then
              echo "## $(echo "$TYPE" | tr '[:lower:]' '[:upper:]')"
              echo
              cat "$MD"
              echo
            fi
          done
          if ! [ -f "$CASE/outputs/per_type/network/report.md" ] && \
             ! [ -f "$CASE/outputs/per_type/endpoint/report.md" ] && \
             ! [ -f "$CASE/outputs/per_type/siem/report.md" ] && \
             ! [ -f "$CASE/outputs/per_type/mobile/report.md" ]; then
            echo "_Aucune section de type détectée._"
          fi
        } > "$CR"
