
name: Assemble Case Report
description: "Assemble les rapports par type en un CaseReport.md"
inputs:
  case_path:
    required: true
    description: "Chemin du case"
runs:
  using: composite
  steps:
    - shell: bash
      name: Assemble
      run: |
        set -e
        CASE="${{ inputs.case_path }}"
        OUT="$CASE/reports"
        mkdir -p "$OUT"
        NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# Case Report" > "$OUT/CaseReport.md"
        echo "_Généré le: $NOW (UTC)_" >> "$OUT/CaseReport.md"
        echo "" >> "$OUT/CaseReport.md"
        for TYPE in network endpoint siem mobile; do
          MD="$CASE/outputs/per_type/$TYPE/report.md"
          if [ -f "$MD" ]; then
            echo "## $(echo $TYPE | tr a-z A-Z)" >> "$OUT/CaseReport.md"
            echo "" >> "$OUT/CaseReport.md"
            cat "$MD" >> "$OUT/CaseReport.md"
            echo "" >> "$OUT/CaseReport.md"
          fi
        done
        if ! grep -q "## " "$OUT/CaseReport.md"; then
          echo "_Aucune section de type détectée._" >> "$OUT/CaseReport.md"
        fi
